const express = require("express");
const router = express.Router();
const userController = require("./controller/userController");
const adminController = require("./controller/adminController");
const supportController = require("./controller/supportController");
const notificationController = require("./controller/notificationController");
const roleController = require("./controller/roleController");
const permissionController = require("./controller/permissionController");
const ticketCategoryController = require("./controller/ticketCategoryController");
const ticketController = require("./controller/ticketController");
const chatController = require("./controller/chatController");
const notifyController = require("./controller/notifyController");
const systemConfigrationController = require("./controller/systemConfigrationController");
const notificationConfigrationController = require("./controller/notificationConfigrationController");
const notificationEventController = require("./controller/notificationEventController");
const categoryController = require("./controller/categoryController");
const auth = require("./middleware/auth");
const subCategoryController = require("./controller/subCategoryController");
const batchController = require("./controller/batchController");
const instructorController = require("./controller/instructorController");
const couponController = require("./controller/couponController");
const bookingController = require("./controller/bookingController");
const bulkBookingController = require("./controller/bulkBookingController");
const enquiryController = require("./controller/enquiryController");
const topicController = require("./controller/topicController");
const bannerController = require("./controller/bannerController");
const courseController = require("./controller/courseController");
const courseTopicController = require("./controller/courseTopicController");

router.use("/user", userController);
router.use("/admin", adminController);
router.use("/instructor", instructorController);
router.use("/enquiry", enquiryController);
router.use("/batch", batchController);
router.use("/support", supportController);
router.use("/topic", topicController);
router.use(auth);

router.use("/notification", notificationController);
router.use("/role", roleController);
router.use("/permission", permissionController);
router.use("/ticket-category", ticketCategoryController);
router.use("/ticket", ticketController);
router.use("/chat", chatController);
router.use("/notify", notifyController);
// router.use("/document", documentController);
router.use("/system-configration", systemConfigrationController);
router.use("/notification-configration", notificationConfigrationController);
router.use("/notification-event", notificationEventController);
router.use("/category", categoryController);
router.use("/sub-category", subCategoryController);
router.use("/coupon", couponController);
router.use("/booking", bookingController);
router.use("/bulk-booking", bulkBookingController);
router.use("/banner", bannerController);
router.use("/course", courseController);
router.use("/course-topic", courseTopicController);


module.exports = router;
